// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyCj9vbrSyMXcymmTReEOCG_OWpmqPu2U',
    appId: '1:790123333160:web:8b951fe78ebfd93f55d71d',
    messagingSenderId: '790123333160',
    projectId: 'bookitnow-b070e',
    authDomain: 'bookitnow-b070e.firebaseapp.com',
    storageBucket: 'bookitnow-b070e.firebasestorage.app',
    measurementId: 'G-5PT87WJ0PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw1FGHoKvImZBEEsImYdGDtVn46kYwPMA',
    appId: '1:790123333160:android:0b585e770aff756855d71d',
    messagingSenderId: '790123333160',
    projectId: 'bookitnow-b070e',
    storageBucket: 'bookitnow-b070e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNOq7Wdv2WHD5mqO5UPHTv_hg1a7xKWjA',
    appId: '1:790123333160:ios:68e8ff25d763b82155d71d',
    messagingSenderId: '790123333160',
    projectId: 'bookitnow-b070e',
    storageBucket: 'bookitnow-b070e.firebasestorage.app',
    iosBundleId: 'com.example.bookitnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNOq7Wdv2WHD5mqO5UPHTv_hg1a7xKWjA',
    appId: '1:790123333160:ios:68e8ff25d763b82155d71d',
    messagingSenderId: '790123333160',
    projectId: 'bookitnow-b070e',
    storageBucket: 'bookitnow-b070e.firebasestorage.app',
    iosBundleId: 'com.example.bookitnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyCj9vbrSyMXcymmTReEOCG_OWpmqPu2U',
    appId: '1:790123333160:web:60e7ef4ba58f69fd55d71d',
    messagingSenderId: '790123333160',
    projectId: 'bookitnow-b070e',
    authDomain: 'bookitnow-b070e.firebaseapp.com',
    storageBucket: 'bookitnow-b070e.firebasestorage.app',
    measurementId: 'G-9L53Y3XGYT',
  );
}
